name: Feature idea
description: Suggest an idea or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What's the idea?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would this be useful?
    validations:
      required: false
